### PR TITLE
Fix grouping

### PR DESCRIPTION
**Pull request by levkar**
This change fixes the parent id and name.

### CODE REVIEW

**Comment by CodazziS** [comment]
Is your modification is compatible with the issue #16 ?
I can't test before next week. Need feedback ...

**Comment by levkar** [comment]
Grouping works fine now for the first grouping (which is normal for gantt) in previous commit groups remains 'undefined'.

Thanks for fast response.

**Comment by CodazziS** [comment]
Hello, 
sorry for long time to responce.
Can you just change your commit please ?
Just verify if the var exist :

```
if (item_parent_id = 'p' + item[group_bys[0]][0] !== undefined && item_parent_name = item[group_bys[0]][1] !== undefined) {
item_parent_id = 'p' + item[group_bys[0]][0];
...
} else {
item_parent_id = 'p' + item[group_bys[0]];
...
}
```

**Comment by levkar** [comment]
isn't checking if (item[group_bys[0]] !== undefined) enough? I deployed it to production and we have no trouble. Let me know if you encountered a problem.

**Pull request merged**
